#---------------------------------------------
# User 
#---------------------------------------------
GET http://localhost:3000/api/users HTTP/1.1
content-type: application/json
###

POST http://localhost:3000/api/users HTTP/1.1
content-type: application/json

{
    "name": "Name-01",
    "email": "name01@email.com"
}
###


#---------------------------------------------
# Order 
#---------------------------------------------#
GET http://localhost:3000/api/orders HTTP/1.1
content-type: application/json
###

GET http://localhost:3000/api/orders/1 HTTP/1.1
content-type: application/json
###

// createOrder 
POST http://localhost:3000/api/orders HTTP/1.1
content-type: application/json

{
    "productId": "Product-01",
    "amount": 99.5
}
###
// updateOrder
POST http://localhost:3000/api/orders/2 HTTP/1.1
content-type: application/json

{
    "productId": "Product-02",
    "amount": 4.5
}
###

#---------------------------------------------
# Transaction 
#---------------------------------------------
// createOrderWithPayment
POST http://localhost:3000/api/orders/transactions HTTP/1.1
content-type: application/json

{
    "productId": "Product-11",
    "amount": 3149.5
}
###
// createUserWithOrderAndPayment
POST http://localhost:3000/api/users/transactions HTTP/1.1
content-type: application/json

{
    "name": "Name-11",
    "email": "name11@email.com",
    "productId": "Product-12",
    "amount": 2149.5
}
###